spring:
  tunnel-socket-starter:
    enabled: false
    tunnels:
      - enabled: true
        endpoint-short-url: /event
        endpoint-description: tunning on socket v1
        hashtag: $event
      - enabled: true
        endpoint-short-url: /action
        endpoint-description: tunning on socket v2
        hashtag: $action
    config:
      enabled: false
      allow-display-skipped-log: false # enable logging for messages
    message:
      fields-ignored:
        - logs
        - privileges
